name: Switch Branch and Diff

on:
  push:
    branches:
      - main

jobs:
  switch-branch-and-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Switch to target branch and run git diff
      run: |
        set -e
        branchName="update_metadata"
        # releaseブランチへのマージPR用ブランチへのチェックアウト
        git checkout -b ${branchName}
        # メタデータ差分ファイル一覧テキスト削除
        if [ -e metadata_diff.txt ]; then
          rm metadata_diff.txt
        fi
        # AppStoreメタデータ情報の差分ファイル一覧出力
        git diff --name-only > metadata_diff.txt
        # AppStoreメタデータ情報の差分ファイル一覧出力
        while read line; do
          if [[ "$line" == *"fastlane/metadata"* ]]; then
           git add "$line"
           git commit -m "[update]AppStoreのメタデータ情報更新 $line"
          fi
        done < metadata_diff.txt
        cat metadata_diff.txt
