name: Xcode - Build & Analyze

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]




jobs:
#  build1:
#    runs-on: ubuntu-latest
#    steps:
#    # actions-timelineはpost処理の最後に実行されないと全てのジョブの情報を収集できないため、
#    # 呼び出しは `actions/checkout` などよりも前の一番最初に行います。

  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
           xcodebuild -scheme TestApp -resultBundlePath TestResults test -destination "platform=iOS Simulator,name=iPhone 14 pro,OS=16.2"

